pipeline {
    agent any
    parameters {
        choice (name: 'BUILD_VARIANT', choices: ['Development', 'Staging', 'Production'], description: '')
        choice (name: 'DELETE_NODE_MODULES', choices: ['Yes', 'No'],  description: '')
    }

    tools {
        nodejs "node-20.15.0"
    }

    stages {
        stage('Set Enviorment Variable') {
            steps {
                script {
                    bat "echo Set Enviorment Variable -> ${params.BUILD_VARIANT}"
                }
            }
        }
        
        stage('pre run') {
            steps {
              bat "echo Build completed for variant: ${params.BUILD_VARIANT} Latest"
            }
        }

        stage('install') {
            steps {
                script {
                    if (${params.DELETE_NODE_MODULES} == 'Yes') {
                        bat 'rmdir /s /q node_modules'
                    }
                    bat 'npm install'
                }
            }
        }

        stage('build') {
            steps {
                bat 'npx nx run mocka-ui:build'
            }
        }
    }

     post {
        always {
            echo 'Cleaning up...'
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
