version: '3'
services:
  nx-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Backend
      - '4200:4200' # Frontend
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/mocka
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - '27017:27017'

  redis:
    image: redis
    ports:
      - '6379:6379'
