services:
  mockoto:
    build:
      context: .
      dockerfile: apps/mockoto/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - mockoto-network
    env_file:
      - apps/mockoto/.env.production

  mockoto-ui:
    build:
      context: . 
      dockerfile: apps/mockoto-ui/Dockerfile
    ports:
      - '3001:80'
    networks:
      - mockoto-network
    env_file:
      - apps/mockoto-ui/.env.production

  mongo:
    image: mongo:latest
    container_name: mockoto-mongo
    networks:
      - mockoto-network
    ports:
      - "27018:27017" 
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: mockoto-redis
    networks:
      - mockoto-network
    ports:
      - "6379:6379" 

networks:
  mockoto-network:

volumes:
  mongo-data:
